<?php
/**
 * Easy Checkout - Magento Extension
 *
 * @package:    EasyCheckout
 * @category:   EcommerceTeam
 * @copyright:  Copyright 2013 EcommerceTeam Inc. (http://www.ecommerce-team.com)
 * @version:    2.0.2
 */

$currentShippingCountry = Mage::getSingleton('ecommerceteam_easycheckout/type_easy')->getQuote()->getShippingAddress()->getCountryId().'';
?>
<ul>
    <li class="fields">
        <div class="field name-firstname">
            <label for="billing:firstname" class="required"><em>*</em><?php echo $this->__('First Name') ?></label>
            <div class="input-box">
                <input type="text" id="billing:firstname" name="billing[firstname]" value="<?php echo $this->getAddress()->getFirstname(); ?>" title="<?php echo $this->__('First Name') ?>" class="input-text required-entry" />
            </div>
        </div>
        <div class="field name-lastname">
            <label for="billing:lastname" class="required"><em>*</em><?php echo $this->__('Last Name') ?></label>
            <div class="input-box">
                <input type="text" id="billing:lastname" name="billing[lastname]" value="<?php echo $this->getAddress()->getLastname(); ?>" title="<?php echo $this->__('Last Name') ?>" class="input-text required-entry" />
            </div>
        </div>
    </li>
    <li class="fields">
        <?php if(!$this->isCustomerLoggedIn()): ?>
        <div class="field email">
            <label for="billing:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
            <div class="input-box">
                <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->htmlEscape($this->getAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
            </div>
        </div>
        <?php else:?>
        <div class="field mail">
            <label class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
            <div class="input-box">
                <input type="text" readonly="readonly" value="<?php echo $this->htmlEscape(Mage::getSingleton('customer/session')->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text readonly" />
            </div>
        </div>
        <?php endif ?>
        <div class="field telephone">
            <label for="billing:telephone" ><?php echo $this->__('Telephone') ?></label>
            <div class="input-box">
                <input type="text" name="billing[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text" id="billing:telephone" />
            </div>
        </div>                
    </li>
    <li class="fields">
        <div class="field company" id="company" style="<?php echo ($currentShippingCountry == "IT")? '' : 'display: none';?>">
            <label for="billing:company"  class="required"><?php echo $this->__('Company') ?></label>
            <div class="input-box">
                <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" />
            </div>
        </div>        
        <div class="field vat" id="vat" style="<?php echo ($currentShippingCountry == "IT")? '' : 'display: none';?>">
            <label for="billing:vat_id"  class="required"><em>*</em><?php echo $this->__('P.Iva/Cod.Fisc.') ?></label>
            <div class="input-box">
                <input type="text" id="billing:vat_id" name="billing[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" class="input-text <?php echo ($currentShippingCountry != "IT")? '' : 'required-entry';?> <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" />
            </div>
        </div>
    </li>    
    <li class="fields">
        <div class="wide street">
            <label for="billing:street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text required-entry" />
            </div>
        </div>
    </li>
    <li class="fields">
        <div class="field">
            <label for="billing:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international required-entry" />
            </div>
        </div>
        
        <div class="field">
            <label for="billing:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="input-text required-entry" id="billing:city" />
            </div>
        </div>                
    </li>
    <li class="fields">        
        <div class="field">
            <label for="billing:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
            <div class="input-box">
                <?php echo $this->getCountryHtmlSelect('billing') ?>
            </div>
        </div>
        <div class="field">
            <label for="billing:region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
            <div class="input-box">
                <select id="billing:region_id" name="billing[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                </select>
                <script type="text/javascript">
                    //<![CDATA[
                    $('billing:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                    //]]>
                </script>
                <input type="text" id="billing:region" name="billing[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
            </div>
        </div>
    </li>
 
    <?php if(!$this->isCustomerLoggedIn()): ?>
    <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
    <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
    <?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
        <?php if ($_dob->isEnabled()): ?>
            <li>
                <div class="field">
                    <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                </div>
            </li>
            <?php endif; ?>
        <?php if ($_gender->isEnabled()): ?>
            <li>
                <div class="field">
                    <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                </div>
            </li>
            <?php endif ?>
        <?php endif ?>    
    <?php endif; ?>
</ul>