<div class="entity-edit color-manager">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo Mage::helper('autelcorto')->__('Manage Colors') ?></h4>
    </div>
    <div class="box">
        <div class="hor-scroll">
            Help i need 
        </div>
    </div>
    <div class="box">
        <div class="hor-scroll">
            <table>
                <tr>
                    <th width="150"><?php echo Mage::helper('autelcorto')->__('Color Label') ?></th>
                    <th width="250"><?php echo Mage::helper('autelcorto')->__('Upload Swatch Image') ?></th>
                    <th><?php echo Mage::helper('autelcorto')->__('Hex Color') ?></th>
                </tr>
                <?php foreach (MAge::helper('autelcorto/media')->getAttributeOptions($this->getAttribute(), 1) as $_attribute): 
                    $_colorOption = Mage::getModel('autelcorto/coloroptions')->Load($_attribute['value'], 'option_id');                
                    ?>
                <tr>
                    <td>
                        <?php echo $_attribute['label']; ?>
                    </td>
                    <td class="value">
                    <?php 
                        $_img = $_colorOption->getImageColorUrl();
                        if ($_img != ""): ?>
                            <a href="<?php echo $_img; ?>" onclick="imagePreview('filename_image_<?php echo $_attribute["value"];?>'); return false;">
                                <img src="<?php echo $_img; ?>" id="filename_image_<?php echo $_attribute['value'];?>" 
                                     title="<?php echo $_attribute['value']?>.jpg" alt="<?php echo $_attribute['label'];?>" 
                                     height="22" width="22" class="small-image-preview v-middle"/>
                            </a> 
                    <?php
                        endif; ?>
                        
                        <input id="filename" name="filename[<?php echo $_attribute['value'];?>]" 
                               value="<?php if ($_img != ''): echo $_attribute['value'].'.jpg'; endif;?>" 
                               type="file" class="input-file" accept="image/jpeg"/>
                    <?php 
                        if ($_img != ""): ?>
                            <span class="delete-image">
                                <input type="checkbox" name="filename_delete[<?php echo $_attribute['value'];?>]" 
                                       value="1" class="checkbox" id="filename_delete_<?php echo $_attribute['value'];?>"/>
                                <label for="filename_delete"> <?php echo $this->__('Delete image');?></label>
                            </span>            
                    <?php
                        endif; ?>                        
                    </td>
                    <td>(#)
                        <input id="color_hex" name="color_hex[<?php echo $_attribute['value'];?>]" 
                               value="<?php echo $_colorOption->getColorHex();?>" 
                               class="input-text" type="text" />
                    </td>
                </tr>
                <?php endforeach; ?>
            </table>
            
        </div>
    </div>
</div>