<?php 
    $_product = $this->getProduct();
    if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views <?php if (count($this->getGalleryImages()) >= 6): echo ' max-six'; endif; ?><?php if ($_product->getData('c_style_fortune_cookie') == ''): echo ' no-style'; endif;?>">    
    <?php foreach ($this->getGalleryImages() as $_image): ?>
        <div>
            <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(700); ?>" rel="more-views" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(105); ?>" width="105" height="105" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
        </div>
    <?php endforeach; ?>
</div>
<script>
    
    $j(document).ready(function() {
        $j(".more-views div a").fancybox({
            autoScale   : true,
            showCloseButton : true
        });        
    });
</script>
<?php endif; ?>
