<?php if (count($this->getGalleryImages()) > 0): ?>
<div class="more-views">    
    <?php foreach ($this->getGalleryImages() as $_image): ?>
        <div>
            <a href="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(700); ?>" rel="more-views" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(100); ?>" width="100" height="100" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" /></a>
        </div>
    <?php endforeach; ?>
</div>
<script>
    
    $j(document).ready(function() {
        $j(".more-views ul li a").fancybox({
            autoScale   : true,
            showCloseButton : true
        });        
    });
</script>
<?php endif; ?>
