<div style="position: relative">
<?php 
$breadcrumbs = $this->getLayout()->getBlock('breadcrumbs');
$breadcrumbs->addCrumb('home', array('label'=>Mage::helper('cms')->__('Home'), 'title'=>Mage::helper('cms')->__('Go to Home Page'), 'link'=>Mage::getBaseUrl()));
$breadcrumbs->addCrumb('impulsebuy', array('label'=>$this->__("Impulse Buy"), 'title'=>$this->__("Impulse By")));
echo $this->getLayout()->getBlock('breadcrumbs')->toHtml();

?>

<img class="impulse-badge" src="<?php echo $this->getSkinUrl('images/impulse_badge.png'); ?>" />

<form class="form-impulsebuy" action="<?php echo $this->getUrl('autelcorto/impulse/impulse')?>" method="post">

<h1><?php echo $this->__("LET'S START!");?></h1>

<div class="question">    
<label for="destination">1. <?php echo $this->__("Where was your last holiday destination?");?></label>
<input type="text" name="destination"></input>
</div>
<div class="question">    
<label for="firstlove">2. <?php echo $this->__("What is the name of your first love?"); ?></label>
<input type="text" name="firstlove"></input>
</div>
<div class="question">    
<label for="livewithout">3. <?php echo $this->__("Can't live without?"); ?></label>
<input type="text" name="livewithout"></input>
</div>

<button type="submit" class="button btn-checkout"><span><span><?php echo $this->__("Submit");?></span></span></button>
</form>
</div><!-- position: relative -->