
<div class="send-friend">
    <div class="message" style="padding: 10px">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('forgotpassword_message')->toHtml() ?>
    </div>
    <form name="lostpasswordform" id="lostpasswordform" action="<?php echo Mage::getStoreConfig("web/unsecure/wp_url")?>wp-login.php?action=lostpassword" method="post">
        <input type="hidden" name="redirect_to" value="<?php echo Mage::getStoreConfig("web/unsecure/wp_url")?>media/">
	<div class="fieldset">
            <ul class="form-list" id="sender_first_name">
                <li class="fields">
                    <div class="field">
                        <label for="user_login" class="required"><em>*</em><?php echo $this->__('Username or E-mail:');?></label>
                        <div class="input-box">
                            <input type="text" name="user_login" id="user_login" class="input-text required-entry validate-email"  value=""/>
                        </div>
                    </div>
                </li>
                <li>
                    <div class="input-box action">
                            <div style="width: 90%">
                                    <div style="float:right">
                                    <a href="#" onclick="$j.fancybox.close(); return false;">Cancel</a> or 
                                    <button id="submit-media-request"type="submit" class="button" style="display:inline">
                                        <span>
                                            <span><?php echo $this->__('Get New Password') ?></span></span></button>
                                    </div>
                            </div>
                    </div>
                </li>                
            </ul>
        </div>
</form>
<script type="text/javascript">
    //<![CDATA[
        var lostpasswordform = new VarienForm('lostpasswordform');
        
</script>