<?php
/**
 * Easy Checkout - Magento Extension
 *
 * @package:    EasyCheckout
 * @category:   EcommerceTeam
 * @copyright:  Copyright 2013 EcommerceTeam Inc. (http://www.ecommerce-team.com)
 * @version:    2.0.2
 */

/** @var $this EcommerceTeam_EasyCheckout_Block_Checkout */
/** @var $helper EcommerceTeam_EasyCheckout_Helper_Easy */
$helper   = Mage::helper('ecommerceteam_easycheckout/easy');
/** @var $customer Mage_Customer_Model_Customer */
$customer = $this->getCustomer();

$cookie = MpsSistemi_Iplocation_Model_Core_Dispatch::RegistryCountry(); 
$checkoutModel = Mage::getSingleton('ecommerceteam_easycheckout/type_easy');

//Forzo la rilettura della quota
$quote = MAge::getModel('sales/quote')->Load($checkoutModel->getQuote()->getId());
$checkoutModel->saveShippingMethod($quote->getShippingAddress()->getShippingMethod());
        

$zone = Mage::getModel('mpslocation/zone')->Load($cookie['zone_id'], 'zone_code');
$shippingList = Mage::Helper('mpslocation')->getCountryFromZone($zone);
$currentShippingCountry = $checkoutModel->getQuote()->getShippingAddress()->getCountryId().'';

?>
<script type="text/javascript">
    //<![CDATA[
    var countryRegions      = <?php echo $this->helper('directory')->getRegionJson(); ?>;
    var checkoutCouponUrl   = '<?php echo $this->getUrl('*/onepage/ajax', array('action'=>'coupon'));?>';

    <?php if (!$customer->getId()):?>
    var loginFormHtml = '<?php echo addslashes(str_replace("\n", "", $this->getChildHtml('login_form')))?>';
    <?php endif;?>
    //]]>
</script>

<?php if (EcommerceTeam_EasyCheckout_Helper_Easy::POSITION_MODE_CART != $helper->getCheckoutMode()):?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php endif;?>  

<div class="easycheckout-onepage-wrap easycheckout-1column" id="easycheckout-form-wrap">

    <div class="page-title">
        <h1><?php echo $this->__('Checkout') ?></h1>        
    </div>

    <?php if (!$customer->getId()):?>
    <ul class="infos-menus">
        <li class="new-users current"><a href="#new-user"><?php echo $this->__('New User');?></a></li>
        <li class="registered-users">
            <a href="<?php echo $this->getUrl('customer/account/login');?>" onclick="TINY.box.show(loginFormHtml,0,260,0,0);return false">
                <?php echo $this->__('Registered');?></a></li>
        <li class="facebook-users">
            <div class="or-fb-connect"> <?php echo $this->__('or');?> </div>
            <?php $block = $this->getLayout()->createBlock('autelsocial/fbconnect')                                                  
                                                  ->setTemplate('autel/social/mini.connect.text.phtml');
                  $block->setRefferType(false);
                  echo $block->toHtml(); ?>
        </li>
        <li class="clear"></li>
    </ul>

    <?php endif;?>    

    <div id="load-info-overlay">&nbsp;</div>
    <?php echo $this->getCmsBlockHtml();?>

    <div class="clear"></div>
    <p class="required">* <?php echo $this->__('Required Fields') ?></p>


    <form action="" method="post" id="easycheckout-form">
        
            <div class="checkout-shipping-area-select">
                <ul>
                    <li class="your-shipping-area">
                        <div class="message"><?php echo $this->__("Your shipping area:");?></div>
                        <div class="shipping-area"><?php echo $zone->getDescription(); ?></div>
                        <div class="change-country">
                            <a href="#" class="mps_link change-country-selector"
                               onclick="$j.fn.selectCountry({'url': '<?php echo $this->getBaseUrl() . "mpslocation/location/select/"; ?>',
                                                         'countryCode': '<?php echo $cookie->getdata('country_code')?>',
                                                         'home': '<?php if ($this->getRequest()->getPathInfo() == "/"): echo "1"; else :echo "0"; endif; ?>',
                                                         'urlref': '<?php echo Mage::helper('core')->urlEncode(Mage::helper('core/url')->getCurrentUrl());?>',
                                                         'enableEsc': true});return false;">
                                <?php echo $this->__('Change country');?>
                            </a>
                        </div>
                    </li>
                    <li class="your-shipping-country">
                        <div class="field form-list">

                                <?php foreach ($shippingList as $k => $v): 
                                        if ($currentShippingCountry == '' && $k == $cookie->getCountryId()):
                                            $currentShippingCountry = $k;      
                                            //$checkoutModel->saveBillingAddress(new Varien_Object(array('country_id' => $k)),null);
                                            //$checkoutModel->saveShippingAddress(new Varien_Object(array('country_id' => $k)),null);
                                        endif;
                                      endforeach; ?>                    

                            <label for="shipping:country_id" class="required"><?php echo $this->__('Country') ?><em>*</em></label>
                            <div class="input-box">
                                <?php  echo $this->getLayout()->createBlock('checkout/onepage_shipping')->getCountryHtmlSelect('shipping-select', $currentShippingCountry) ?>
                            </div>                    
                        </div>
                    </li>
                </ul>
            </div>
        
        
        <?php if ($helper->canShip()):?>   
        <?php   $blockSipping = $this->getChild('shipping_method');
                $blockSipping->setData('current_shipping_country', $currentShippingCountry);
                echo $blockSipping->toHtml();?>
        <?php endif;?>
        <div class="clearer"></div>
        <?php echo $this->getChildHtml('billing_address');?>

        <?php if ($helper->canShip() && $helper->differentShippingEnabled()):?>
            <?php echo $this->getChildHtml('shipping_address');?>
        <?php endif;?>

        
        <?php //echo $this->getReviewBlock();?>
        
        <?php echo $this->getChildHtml('echeckout_cart'); ?>
        
        
        <table id="easycheckout-shipping-payment-step">
            <tbody>
            <tr>
                <td class="payment-method" id="payment-method-wrapper"><?php echo $this->getChildHtml('payment_method');?></td>
                <?php if ($helper->couponEnabled()):?>
                <td class="methods-separator">&nbsp;</td>
                <td class="checkout-coupon" id="coupon-wrapper">
                    <?php echo $this->getChildHtml('echeckout_coupon');?>
                </td>                
                <?php endif;?>                                                         
                           
            </tr>
            </tbody>
        </table>

        <?php echo $this->getChildHtml('totals');?>
        <div class="clearer"></div>
        <div class="button-set place-order-buttons">
            <?php if ($helper->showSubscribe()):?>
            <div class="subscribe-btn-wrapper"><label><input type="checkbox" name="subscribe" value="1"/> <?php echo $this->__('Subscribe to newsletter');?></label></div>
            <?php endif;?>
                
            <div class="submit-btn-wrapper">
                <div><button id="submit-btn" type="submit" title="<?php echo $this->__('Place Order') ?>" class="button btn-checkout"><span><span><?php echo $this->__('Place Order') ?></span></span></button></div>
                <span id="checkout-loadinfo" class="loadinfo">&nbsp;</span>
            </div>
        </div>
        
        <div class="agreements">
            <?php echo $this->getChildHtml('agreements') ?>
        </div>

        
    </form>
</div>


<script type="text/javascript">
    //<![CDATA[
    var checkout = new EasyCheckout(
        {
            "mode": "<?php echo $this->getMode();?>",
            "formId":"easycheckout-form",
            "saveAddressUrl":"<?php echo $this->getUrl('*/*/saveAddress');?>",
            "saveShippingMethodUrl":"<?php echo $this->getUrl('*/*/saveShippingMethod');?>",
            "savePaymentMethodUrl":"<?php echo $this->getUrl('*/*/savePaymentMethod');?>",
            "saveCouponCodeUrl":"<?php echo $this->getUrl('*/*/saveCouponCode');?>",
            "reloadCartUrl": "<?php echo $this->getBaseUrl() . 'checkout/cart/updatePost/'; ?>",
            "saveOrderUrl":"<?php echo $this->getUrl('*/*/saveOrder');?>",
            "successUrl":"<?php echo $this->getUrl('*/*/success');?>",
            "agreementsMessage": "<?php echo $helper->__("Please agree to all the terms and conditions before placing the order.");?>",
            "responseFailureMsg":"<?php echo addslashes($helper->__("Warning server has returned error! Code: %code%. Please, contact with site administration."))?>",
            "unknownServerErrorMsg":"<?php echo addslashes($helper->__("Unknown server error! Please, contact with site administration."))?>",
            "skin":"<?php echo $this->isModernSkin() ? 'modern' : 'default';?>"
        }
    );

    // fix for stupid extensions
    var accordion = {currentSection:0, openSection:function(){}, container:{readAttribute:function(){}}};
    checkout.accordion = accordion;

    // Fix for save compatibility with original checkout and some extensions
    var review = new Review(
        '<?php echo $this->getUrl('*/*/saveOrder') ?>',
        '<?php echo $this->getUrl('*/*/success') ?>',
        $('checkout-agreements')
    );

    //]]>
</script>
