<?php
/**
 * Easy Checkout - Magento Extension
 *
 * @package:    EasyCheckout
 * @category:   EcommerceTeam
 * @copyright:  Copyright 2013 EcommerceTeam Inc. (http://www.ecommerce-team.com)
 * @version:    2.0.2
 */

/** @var $this EcommerceTeam_EasyCheckout_Block_Onepage_Shipping */
if($this->canShow()): 
    $checkoutModel = Mage::getSingleton('ecommerceteam_easycheckout/type_easy');
    $forceNewAddress = false;
    if ($this->customerHasAddresses()):
        //Gli passo anche la country che ho impostato sopra in modo che cerco di prendere un indirizzo buono per la country
        $addressLists = $this->getAddressesHtmlSelect('shipping', $this->getData('current_shipping_country'));
        if ($addressLists == ''):            
            //Se non ho indirizzi buoni ne forzo uno con la country di default
            $forceNewAddress = true;        
            $checkoutModel->saveShippingAddress(new Varien_Object(array('country_id' => $this->getData('current_shipping_country'))),null);
        endif;
    endif;
        
?>
<div class="easy-step shipping-address"
    <?php if($this->isThreeColsMode()):?>id="shipping-address-wrapper" <?php endif;?>
    <?php if($this->isThreeColsMode() && $this->someAsBilling()):?> style="display:none;" <?php endif;?>>
    
    <h2><?php echo $this->__('Shipping Address')?>:
        <?php if(!$this->isThreeColsMode()):?>
        <label>
            <input type="checkbox" name="billing[use_for_shipping]" id="billing_use_for_shipping_yes" value="1" <?php if($this->someAsBilling() && !$forceNewAddress):?> checked="checked" <?php endif;?> class="radio" />
            <span><?php echo $this->__('Same as Billing Address');?></span>
        </label>
        <?php endif;?>
    </h2>

    <ul <?php if(!$this->isThreeColsMode()):?>id="shipping-address-wrapper" <?php if($this->someAsBilling() && !$forceNewAddress):?> style="display:none;" <?php endif;?> <?php endif;?> class="form-list address-form-list" >
        <?php if ($this->customerHasAddresses() && !$forceNewAddress): ?>
           <li class="wide">
               <label style="text-align:left;width:auto;float:none;" for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book.') ?></label>
               <div class="input-box address-select-box">
                   <?php echo $addressLists; ?>
               </div>
           </li>
        <?php endif ?>
        <li id="shipping-new-address-form"<?php if ($this->customerHasAddresses() && !$forceNewAddress): ?> style="display:none;"<?php endif ?>>
            <fieldset>
                <?php echo $this->getChildHtml('address');?>
            </fieldset>
        </li>
    </ul>
    <script type="text/javascript">
    //<![CDATA[
        var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions, undefined, 'shipping:postcode');
    //]]>
    </script>
</div>
<?php endif;?>