<?php
/**
 * Easy Checkout - Magento Extension
 *
 * @package:    EasyCheckout
 * @category:   EcommerceTeam
 * @copyright:  Copyright 2013 EcommerceTeam Inc. (http://www.ecommerce-team.com)
 * @version:    2.0.2
 */

/** @var $this EcommerceTeam_EasyCheckout_Block_Onepage_Shipping */

$shipping = $this->getQuote()->getShippingAddress()->getShippingMethod();         

if($this->canShow()): ?>
<div class="easy-step shipping-address"
    id="shipping-address-wrapper"
    <?php if($shipping == "autel_pikup_in_milan_boutique" || $shipping == "autel_pikup_in_paris_boutique"):?> style="display:none;" <?php endif;?>>
    
    <h2><?php echo $this->__('Shipping Address')?>:
        <?php if(!$this->isThreeColsMode()):?>
        <label>
            <input type="checkbox" name="billing[use_for_shipping]" id="billing_use_for_shipping_yes" value="1" <?php if($this->someAsBilling()):?> checked="checked" <?php endif;?> class="radio" />
            <span><?php echo $this->__('Same as Billing Address');?></span>
        </label>
        <?php endif;?>
    </h2>

    <ul <?php if(!$this->isThreeColsMode()):?>id="shipping-address-from-wrapper" <?php if($this->someAsBilling()):?> style="display:none;" <?php endif;?> <?php endif;?> class="form-list address-form-list" >
        <?php if ($this->customerHasAddresses() && Mage::getSingleton('customer/session')->isLoggedIn()): ?>
           <li class="wide">
               <label style="text-align:left;width:auto;float:none;" for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book.') ?></label>
               <div class="input-box address-select-box">
                   <?php echo $this->getAddressesHtmlSelect('shipping') ?>
               </div>
           </li>
        <?php else: ?>
           <li class="wide">
               <label style="text-align:left;width:auto;float:none;" for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book.') ?></label>
               <div class="input-box address-select-box">
                   <!-- mettere la selezione per creare/uguale --->
               </div>
           </li>
        <?php endif ?>
        <li id="shipping-new-address-form">
            <fieldset>
                <?php echo $this->getChildHtml('address');?>
            </fieldset>
        </li>
    </ul>
    <script type="text/javascript">
    //<![CDATA[
        var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', countryRegions, undefined, 'shipping:postcode');
    //]]>
    </script>
</div>
<?php endif;?>