<?php
/**
 * Easy Checkout - Magento Extension
 *
 * @package:    EasyCheckout
 * @category:   EcommerceTeam
 * @copyright:  Copyright 2013 EcommerceTeam Inc. (http://www.ecommerce-team.com)
 * @version:    2.0.2
 */
?>
<ul>
    <li class="fields">
        <div class="field name-firstname">
            <label for="shipping:firstname" class="required"><em>*</em><?php echo $this->__('First Name') ?></label>
            <div class="input-box">
                <input type="text" id="shipping:firstname" name="shipping[firstname]" value="<?php echo $this->getAddress()->getFirstname(); ?>" title="<?php echo $this->__('First Name') ?>" class="input-text required-entry" />
            </div>
        </div>
        <div class="field name-lastname">
            <label for="shipping:lastname" class="required"><em>*</em><?php echo $this->__('Last Name') ?></label>
            <div class="input-box">
                <input type="text" id="shipping:lastname" name="shipping[lastname]" value="<?php echo $this->getAddress()->getLastname(); ?>" title="<?php echo $this->__('Last Name') ?>" class="input-text required-entry" />
            </div>
        </div>
    </li>
    <li class="fields">
        <div class="field">
            <label for="shipping:street1" class="required"><em>*</em><?php echo $this->__('Street line') ?> 1</label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="input-text required-entry" />
            </div>
        </div>
        <div class="field">
            <label for="shipping:street1"><?php echo $this->__('Street line') ?> 2</label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('Street Address %s', 2) ?>" name="shipping[street][]" id="shipping:street2" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(2)) ?>" class="input-text" />
            </div>
        </div>
    </li>
    <li class="fields">
        <div class="field">
            <label for="shipping:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="input-text required-entry" id="shipping:city" />
            </div>
        </div>
        <div class="field">
            <label for="shipping:region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
            <div class="input-box">
                <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>" class="validate-select" style="display:none;">
                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                </select>
                <script type="text/javascript">
                //<![CDATA[
                    $('shipping:region_id').setAttribute('defaultValue',  "<?php echo $this->getAddress()->getRegionId() ?>");
                //]]>
                </script>
                <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->htmlEscape($this->getAddress()->getRegion()) ?>"  title="<?php echo $this->__('State/Province') ?>" class="input-text" style="display:none;" />
            </div>
        </div>
    </li>
    <li class="fields">
        <div class="field">
            <label for="shipping:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode()) ?>" class="input-text validate-zip-international required-entry" />
            </div>
        </div>
        <div class="field">
            <label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
            <div class="input-box">
                <?php echo $this->getCountryHtmlSelect('shipping') ?>
            </div>
        </div>
    </li>
    <li class="fields">
        <div class="field">
            <label for="shipping:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
            <div class="input-box">
                <input type="text" name="shipping[telephone]" value="<?php echo $this->htmlEscape($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="input-text required-entry" id="shipping:telephone" />
            </div>
        </div>
        <div class="field">
            <label for="shipping:fax"><?php echo $this->__('Fax') ?></label>
            <div class="input-box">
                <input type="text" name="shipping[fax]" value="<?php echo $this->htmlEscape($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="input-text" id="shipping:fax" />
            </div>
        </div>
    </li>

    <li class="fields">
        <div class="field">
            <label for="shipping:company"><?php echo $this->__('Company') ?></label>
            <div class="input-box">
                <input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->htmlEscape($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text" />
            </div>
        </div>
        
    </li>
</ul>
