<?php if (sizeof($this->_menu) > 0): ?>
<ul id="menu-header-list">
    <?php foreach ($this->_menu as $menu):?>
    <?php if ($this->isToPrint($menu)): ?>
        <li class="<?php if ($this->isSelectMenu($menu)):?>is-menu-select<?php endif; ?>">
            <a mps-type="async-link" class="rainbow-link header-menu" href="<?php echo $this->getLink($menu);?>" title="<?php echo $menu['name'];?>">
                <?php echo $this->htmlEscape($menu['name']);?>
            </a>
        </li>
    <?php endif;?>
    <?php endforeach; ?>        
</ul>
<script type="text/javascript">
    decorateList('menu-header-list', 'none-recursive');
    jQuery('document').ready(function () {
        menuTimer = jQuery('#menu-header-list li.is-menu-select a').RainbowLink("", true, true );
    });
</script>
<?php endif; ?>

