<script type="text/javascript" src="<?php echo $this->getSkinUrl("js/social.js");?>"/>
<div class="pop-up-login">
<div>
    <div class="block block-login p-left">
        <div class="block-title">
            <strong><span><?php echo $this->__('New Customer') ?></span></strong>
        </div>
        <div class="block-content">
            <p><?php echo $this->__("Please create an account to");?>:</p>
            <ul class="form-list">
                <li>
                    <p><?php echo $this->__("Checkout faster");?></p>
                </li>
                <li>
                    <p><?php echo $this->__("View and track your orders");?></p>
                </li>
                <li>
                    <p><?php echo $this->__("Receive newsletters");?></p>
                </li>
                <li>
                    <p><?php echo $this->__("Access exclusive collection");?></p>
                </li>
                <li>
                    <p><?php echo $this->__("Invitations to special events");?></p>
                </li>
                <li>
                    <p><?php echo $this->__("Seasonal sale offers");?></p>
                </li>                
            </ul>
			<div class="action">
				<button type="button" title="<?php echo $this->__('Create an Account');?>" 
						class="button btn-checkout" 
						onclick="window.location='<?php echo $this->getUrl('customer/account/create');?>';"><span><span><?php echo $this->__("Join");?></span></span></button>
			</div>
        </div>
    </div>
    <div class="block block-login p-right">
        <div class="block-title">
            <strong><span><?php echo $this->__('Registered Customer') ?></span></strong>
        </div>        
        <form action="<?php echo $this->getPostActionUrl() ?>" method="post">
            <div class="block-content">
                <p><?php echo $this->__("If you have an account with us, please log in");?>:</p>
                <div>
                    <label for="mini-login"><?php echo $this->__('Email:') ?></label>
                    <input type="text" name="login[username]" id="mini-login" class="input-text" />
                </div>
                <div>
                    <label for="mini-password"><?php echo $this->__('Password:') ?></label>
                    <input type="password" name="login[password]" id="mini-password" class="input-text" />
                    <input type="hidden" name="<?php echo Mage_Customer_Helper_Data::REFERER_QUERY_PARAM_NAME;?>"
                    	   value="<?php echo Mage::helper('core')->urlEncode($_SERVER['HTTP_REFERER']);?>"/>
                </div>
                <div class="actions">
                    <br/>
                    <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
                    <div class="clear"></div>
                    <button type="submit" class="button"><span><span><?php echo $this->__('Login') ?></span></span></button>
		    <div class="clear"></div>
                    <?php echo $this->getLayout()->createBlock('autelsocial/fbconnect')
                                                  ->setTemplate('autel/social/mini.connect.phtml')
                                                  ->toHtml(); ?>
                </div>
            </div>
        </form>
    </div>
</div>
</div>
